const permissionsSlugs = [
  '*.*',
  'SERVICE.*',
  'SERVICE.CREATE',
  'SERVICE.UPDATE',
  'SERVICE.DELETE',
  'SECTION.*',
  'SECTION.CREATE',
  'SECTION.UPDATE',
  'SECTION.DELETE',
  'REVIEW.*',
  'REVIEW.ACCEPT',
  'REVIEW.UPDATE',
  'REVIEW.DELETE',
  'ORDER.*',
  'ORDER.GET',
  'ORDER.CREATE',
  'ORDER.UPDATE',
  'ORDER.DELETE',
  'LOGO.UPDATE',
  'THEME.UPDATE',
  'INFO.UPDATE',
];

module.exports = permissionsSlugs;
